name: Java CI with Gradle

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: /usr/bin/bash -e {0}
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/11.0.23-9/x64
        working-directory: /home/runner/work/DeployPractice/DeployPractice/./gradlew

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: /home/runner/work/DeployPractice/DeployPractice/./gradlew

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker build -t spring-cicd .
          docker tag spring-cicd protox123/spring-cicd:${GITHUB_SHA::7}
          docker push protox123/spring-cicd:${GITHUB_SHA::7}